apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: systemrules.datasource.sentinel.com
spec:
  group: datasource.sentinel.com
  names:
    kind: SystemRules
    listKind: SystemRulesList
    plural: systemrules
    singular: systemrules
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SystemRules is the Schema for the systemrules API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SystemRulesSpec defines the desired state of SystemRules
          properties:
            rules:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  metricType:
                    type: integer
                  strategy:
                    type: integer
                  triggerCount:
                    type: string
                required:
                - metricType
                - strategy
                - triggerCount
                type: object
              type: array
          required:
          - rules
          type: object
        status:
          description: SystemRulesStatus defines the observed state of SystemRules
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
