apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hotspotrules.datasource.sentinel.com
spec:
  group: datasource.sentinel.com
  names:
    kind: HotspotRules
    listKind: HotspotRulesList
    plural: hotspotrules
    singular: hotspotrules
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HotspotRules is the Schema for the hotspotrules API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HotspotRulesSpec defines the desired state of HotspotRules
          properties:
            rules:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  burstCount:
                    format: int64
                    type: integer
                  controlBehavior:
                    type: integer
                  durationInSec:
                    format: int64
                    type: integer
                  maxQueueingTimeMs:
                    description: MaxQueueingTimeMs is the max queueing time in Throttling
                      ControlBehavior
                    format: int64
                    type: integer
                  metricType:
                    type: integer
                  paramIndex:
                    description: ParamIndex is the index in context arguments slice.
                    type: integer
                  paramsMaxCapacity:
                    format: int64
                    type: integer
                  resource:
                    type: string
                  specificItems:
                    additionalProperties:
                      format: int64
                      type: integer
                    description: compress SpecificValue as string
                    type: object
                  threshold:
                    format: int64
                    type: integer
                required:
                - burstCount
                - controlBehavior
                - durationInSec
                - maxQueueingTimeMs
                - metricType
                - paramIndex
                - paramsMaxCapacity
                - resource
                - specificItems
                - threshold
                type: object
              type: array
          required:
          - rules
          type: object
        status:
          description: HotspotRulesStatus defines the observed state of HotspotRules
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
